// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQxWiBvBf8BaauUwFP_Ej5SioMIrQd4NQ',
    appId: '1:260800558973:web:9815c76bf140b1a4b93e14',
    messagingSenderId: '260800558973',
    projectId: 'twasol-42cdf',
    authDomain: 'twasol-42cdf.firebaseapp.com',
    storageBucket: 'twasol-42cdf.appspot.com',
    measurementId: 'G-PJK0VV2ZZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtz3gBNeS3sySzcqCoA7CxD3FpBiwUs5s',
    appId: '1:260800558973:android:757c2b3a3c6a44e6b93e14',
    messagingSenderId: '260800558973',
    projectId: 'twasol-42cdf',
    storageBucket: 'twasol-42cdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3e0nNAxAl0P-vW7toEE48WsRjBfLuMjE',
    appId: '1:260800558973:ios:cac8d22c903f2346b93e14',
    messagingSenderId: '260800558973',
    projectId: 'twasol-42cdf',
    storageBucket: 'twasol-42cdf.appspot.com',
    iosBundleId: 'com.example.twasol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3e0nNAxAl0P-vW7toEE48WsRjBfLuMjE',
    appId: '1:260800558973:ios:cac8d22c903f2346b93e14',
    messagingSenderId: '260800558973',
    projectId: 'twasol-42cdf',
    storageBucket: 'twasol-42cdf.appspot.com',
    iosBundleId: 'com.example.twasol',
  );
}
